---
title: 메서드에 예외 선언하기
categories:
  - Develop
tags:
  - Java
  - 자바의 정석 기초편
---
## 메서드에 예외 선언하기

예외를 처리하는 방법 : 직접 처리하기 (try-catch문), 알리기 (예외 선언하기), 무시 (빈 catch문)

- 예외를 처리하는 방법 : try-catch문, 예외 선언하기
- 메서드가 호출시 발생가능한 예외를 <u>호출하는 쪽에 알리는 것</u>

  (예외를 발생시키는 키워드 **throw**와 예외를 메서드에 선언할 때 쓰이는 **throws**를 잘 구별해야한다.)

```java
void method() throws Exception1, Exception2, ... ExceptionN {
		// 메서드의 내용
}
// method()에서 Exception과 그 자손 예외 발생 가능
void method() throws Exception { // 모든 종류의 예외가 발생가능 (오버라이딩)
  	// 메서드의 내용
}
```
>
> 잠깐 복습
> **오버라이딩의 규칙**
>
> 1. 선언부의 일치
> 2. 접근제어자보다 좁게 불가능
> 3. 조상보다 많은 예외선언 불가능
>

메서드에 예외 선언하기 - Ex8_9

```java
public class Ex8_9 { // 이것은 try-catch문이 있어야지 예외가 처리 될 수 있는 것이다.
    public static void main(String[] args) throws Exception {
        method1(); // 같은 클래스내의 static멤버이므로 객체생성없이 직접 호출가능.
    }	// main메서드의 끝

    static void method1() throws Exception {
        method2();
    }	// method1의 끝

    static void method2() throws Exception {
        throw new Exception();
    }	// method2의 끝
}

// 결과 : JVM의 기본예외처리기가 출력한 것이다. (예외 발생 당시 상황 - 호출스택 상황을 담고 있다.)

// Exception in thread "main" java.lang.Exception
//	at ch08.Ex8_9.method2(Ex8_9.java:11)
//	at ch08.Ex8_9.method1(Ex8_9.java:7)
//	at ch08.Ex8_9.main(Ex8_9.java:3)
```

메서드에 예외 선언하기 - Ex8_10

```java
import java.io.File;

public class Ex8_10 {
    public static void main(String[] args) {
        try { // 직접처리 (try-catch)
            File f = createFile(args[0]); // args[0]은 위의 String[] args에 들어가는 것이다.
            System.out.println( f.getName()+"파일이 성공적으로 생성되었습니다.");
        } catch (Exception e) {
            System.out.println(e.getMessage()+" 다시 입력해 주시기 바랍니다.");
        }
    } // main메서드의 끝

    static File createFile(String fileName) throws Exception {
        if (fileName==null || fileName.equals("")) // args[0]에 빈 문자열을 넣거나, null일 경우에
            throw new Exception("파일이름이 유효하지 않습니다."); // 예외선언
        File f = new File(fileName); //  File클래스의 객체를 만든다.
        // File객체의 createNewFile메서드를 이용해서 실제 파일을 생성한다.
        f.createNewFile();
        return f; // 생성된 객체의 참조를 반환한다.
    }	// createFile메서드의 끝
}	// 클래스의 끝

// 결과 : 0 다시 입력해 주시기 바랍니다.

```

예외 처리와 예외 선언은 다른 것이다.

Ex8_10의 예외선언을 직접처리했을 경우 - Ex8_15

```java
package ch08;

import java.io.File;
import java.io.IOException;

public class Ex8_15 {
    public static void main(String[] args) {
            File f = createFile("");
            System.out.println( f.getName()+" 파일이 성공적으로 생성되었습니다.");
    } // main메서드의 끝

    static File createFile(String fileName) {
        try {
            if (fileName == null || fileName.equals("")) // File f에 빈 문자열을 넣거나, null일 경우에
                throw new Exception("파일이름이 유효하지 않습니다."); // 직접처리 (try-catch)
        } catch (Exception e) {
            fileName = "제목없음.txt";
        }
        File f = new File(fileName); //  File클래스의 객체를 만든다.
        // File객체의 createNewFile메서드를 이용해서 실제 파일을 생성한다.
        try {
        f.createNewFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return f; // 생성된 객체의 참조를 반환한다.
    }	// createFile메서드의 끝
}	// 클래스의 끝

// 결과 : 제목없음.txt 파일이 성공적으로 생성되었습니다.
```

작업을 발생하는 곳이 예외를 처리하는 게 맞는지, 호출하는 곳이 처리하는 게 맞는지 생각해야한다.

## Finally 블럭

예외발생여부와 관계없이 수행되어야 하는 코드를 넣는다.
	<u>try블럭 안에 return문이 있어서 try블럭을 벗어나갈 때도, finally블럭이 실행된다.</u>

```java
try {
  	// 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
  	// 예외처리를 위한 문장을 적는다.
} finally {
  	// 예외의 발생여부에 관계없이 항상 수행되어야하는 문장들을 넣는다.
  	// finally 블럭은 try-catch문의 맨 마지막에 위치해야한다.
}
```
Finally 블럭의 예 
```java
try {
  	startInstall();
  	copyFiles();
  	deleteTempFiles(); // 임시파일 삭제 - 예외발생
} catch (Exception e) {
  	e.printStackTrace();
  	deleteTempfiles();
} // try-catch의 끝
```
```java
try {
  	startInstall();
  	copyFiles();
} catch (Exception e) {
  	e.printStackTrace();
  	deleteTempfiles();
} finally {
  	deleteTempFiles(); // 코드 중복 제거
} // try-catch의 끝
```